// for quiz actions

export const FETCH_QUIZES_START = 'FETCH_QUIZES_START'
export const FETCH_QUIZES_SUCCESS = 'FETCH_QUIZES_SUCCESS'
export const FETCH_QUIZES_ERROR = 'FETCH_QUIZES_ERROR'
export const FETCH_QUIZ_SUCCESS = 'FETCH_QUIZ_SUCCESS'

export const QUIZ_SET_STATE = 'QUIZ_SET_STATE'
export const FINISH_QUIZ = 'FINISH_QUIZ'
export const QUIZ_NEXT_QUESTION = 'QUIZ_NEXT_QUESTION'

export const QUIZ_RETRY = 'QUIZ_RETRY'

export const ERROR_FETCH_QUIZES = "ERROR_FETCH_QUIZES"

export const REMOVE_QUIZ = 'REMOVE_QUIZ'


// for create actions
export const ADD_QUIZ_NAME = 'ADD_QUIZ_NAME'
export const CREATE_QUIZ_QUESTION = 'CREATE_QUIZ_QUESTION'
export const RESET_QUIZ_CREATION = 'RESET_QUIZ_CREATION'
export const ERROR_QUIZ_CREATION = 'ERROR_QUIZ_CREATION'

// for auth

export const AUTH_SUCCESS = 'AUTH_SUCCESS'
export const AUTH_LOGOUT = 'AUTH_LOGOUT'

export const AUTH_FAILED = 'AUTH_FAILED'

export const REFRESH_ERR_AUTH = 'REFRESH_ERR_AUTH'
export const REFRESH_ERR_QUIZ = 'REFRESH_ERR_QUIZ'
export const REFRESH_ERR_CREATE = 'REFRESH_ERR_CREATE'
